// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrAbT10bB-Hz4pvI7TqEGJMI_2VzKDZk',
    appId: '1:455577115636:web:26046098270af386e377a1',
    messagingSenderId: '455577115636',
    projectId: 'yoklama-sistemi-d808c',
    authDomain: 'yoklama-sistemi-d808c.firebaseapp.com',
    storageBucket: 'yoklama-sistemi-d808c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKYCx-lW7kIx-rLflu0NWxBUIvfNf1oLo',
    appId: '1:455577115636:android:4379a86100503afbe377a1',
    messagingSenderId: '455577115636',
    projectId: 'yoklama-sistemi-d808c',
    storageBucket: 'yoklama-sistemi-d808c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmnHC3NfdOWylir_7lDIfhGubjyMMCQQ',
    appId: '1:455577115636:ios:c1bb5de3cd8c5770e377a1',
    messagingSenderId: '455577115636',
    projectId: 'yoklama-sistemi-d808c',
    storageBucket: 'yoklama-sistemi-d808c.firebasestorage.app',
    iosBundleId: 'com.example.yoklamaSistemi',
  );
}
